name: Deploy static content to Pages

on:
  # Trigger del workflow sui push alla branch principale
  push:
    branches: ["main"]

  # Permette di eseguire il workflow manualmente dalla tab Actions
  workflow_dispatch:

# Imposta le permessi del GITHUB_TOKEN per il deploy su GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Concorrenza: permette di non annullare il deploy in corso e di saltare quelli in coda
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Carica l'intero repository o solo la cartella di build, se necessario
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
